function comdifclutmaps(path1,path2,output)
    mkdir(output);
    sub1=dir(path1);
    sub1(1:2)=[];
    sub2=dir(path2);
    sub2(1:2)=[];
    % sub3=dir(path3);
    % sub3(1:2)=[];
    samplesize1=size(sub1,1);
    samplesize2=size(sub2,1);
    % samplesize3=size(sub3,1);
    % ANMoverlapmap(path1);
    % ANMoverlapmap(path2);
    overlapmappath1=[path1,'_nan_bin_overlap/merge.nii.gz'];
    overlapmappath2=[path2,'_nan_bin_overlap/merge.nii.gz'];
    % overlapmappath3=[path3,'_nan_bin_overlap/merge.nii.gz'];
    system(strcat('fslmaths "',overlapmappath1,'" -thr +',num2str(0.6*samplesize1),' -bin "',output,'overlapmap1_+.nii.gz"'));
    system(strcat('fslmaths "',overlapmappath1,'"  -uthr -',num2str(0.6*samplesize1),' -mul -1 -bin "',output,'overlapmap1_-.nii.gz"'));
    system(strcat('fslmaths "',overlapmappath2,'" -thr +',num2str(0.6*samplesize2),' -bin "',output,'overlapmap2_+.nii.gz"'));
    system(strcat('fslmaths "',overlapmappath2,'"  -uthr -',num2str(0.6*samplesize2),' -mul -1 -bin "',output,'overlapmap2_-.nii.gz"'));
    % system(strcat('fslmaths "',overlapmappath3,'" -thr +',num2str(0.6*samplesize3),' -bin "',output,'overlapmap3_+.nii.gz"'));
    % system(strcat('fslmaths "',overlapmappath3,'"  -uthr -',num2str(0.6*samplesize3),' -mul -1 -bin "',output,'overlapmap3_-.nii.gz"'));
    system(strcat('fslmaths "',output,'overlapmap1_+.nii.gz" -add "',output,'overlapmap1_-.nii.gz" -mul 1 "',output,'overlapmap1.nii.gz"'));
    system(strcat('fslmaths "',output,'overlapmap2_+.nii.gz" -add "',output,'overlapmap2_-.nii.gz" -mul 2 "',output,'overlapmap2.nii.gz"'));
    % system(strcat('fslmaths "',output,'overlapmap3_+.nii.gz" -add "',output,'overlapmap3_-.nii.gz" -mul 4 "',output,'overlapmap3.nii.gz"'));
    system(strcat('fslmaths "',output,'overlapmap1.nii.gz" -add "',output,'overlapmap2.nii.gz" "',output,'overlapmap.nii.gz"'));
    v=spm_vol(strcat(output,'overlapmap.nii.gz'));
    y=spm_read_vols(v);
    y=(-y).*(y-1.5).*(y-3);
    v.fname=strcat(output,'sub.nii');
    spm_write_vol(v,y);
end
