function [GOnumber_all,GOterm_all,NES_all,fdrp_all,index,experiment]=integrate_GSEA(analysispath,fdrpthr,topnumer)
    sub=dir(analysispath);
    GOnumber_all={};
    GOterm_all={};
    NES_all=[];
    fdrp_all=[];
    index=[];
    experiment=[];
    for i=1:size(sub,1)
        disp(i)
        filename=strcat(sub(i).folder,'/',sub(i).name);
        data=readtable(filename);
        fdrp=table2array(data(:,"Var8"));
        fdrp(isnan(fdrp))=0;
        fdrp(fdrp>fdrpthr)=1;
        change_point=zeros(size(fdrp,1),1);
        for j=1:(size(fdrp,1)-1)
            if fdrp(j)>fdrp(j+1)
               change_point(j,1)=1;
            end
        end
        change_index=find(change_point==1);
        change_index=[0,change_index']';
        for k=1:size(change_index,1)
            if k<size(change_index,1)
                NES=table2array(data(change_index(k)+1:change_index(k+1),"Var6"));
                GOnumber=data(change_index(k)+1:change_index(k+1),"Var1");
                GOterm=data(change_index(k)+1:change_index(k+1),"Var2");
                fdrp_change=fdrp(change_index(k)+1:change_index(k+1),1);
                sigfdrp_change=fdrp_change(find(fdrp_change<1));
                sigGOnumber=GOnumber(find(fdrp_change<1),1);
                sigGOterm=GOterm(find(fdrp_change<1),1);
                sigNES=NES(find(fdrp_change<1));
                po_sigNES=find(sigNES>0);
                ne_sigNES=find(sigNES<0);
                if size(po_sigNES,1)>topnumer
                    [~,index_po]=maxk(sigNES(po_sigNES),topnumer);
                    sigGOnumpo=sigGOnumber(po_sigNES(index_po),1);
                    sigGOtermpo=sigGOterm(po_sigNES(index_po),1);
                    sigNESpo=sigNES(po_sigNES(index_po),1);
                    sigfdrppo=sigfdrp_change(po_sigNES(index_po),1);
                else
                    sigGOnumpo=sigGOnumber(po_sigNES,1);
                    sigGOtermpo=sigGOterm(po_sigNES,1);
                    sigNESpo=sigNES(po_sigNES,1);
                    sigfdrppo=sigfdrp_change(po_sigNES,1);
                end
                if size(ne_sigNES,1)>topnumer
                    [~,index_ne]=mink(sigNES(ne_sigNES),topnumer);
                    sigGOnumne=sigGOnumber(ne_sigNES(index_ne),1);
                    sigGOtermne=sigGOterm(ne_sigNES(index_ne),1);
                    sigNESne=sigNES(ne_sigNES(index_ne),1);
                    sigfdrpne=sigfdrp_change(ne_sigNES(index_ne),1);
                else
                    sigGOnumne=sigGOnumber(ne_sigNES,1);
                    sigGOtermne=sigGOterm(ne_sigNES,1);
                    sigNESne=sigNES(ne_sigNES,1);
                    sigfdrpne=sigfdrp_change(ne_sigNES,1);
                end
                sigGOnum_forone=vertcat(sigGOnumpo,sigGOnumne);
                sigGOterm_forone=vertcat(sigGOtermpo,sigGOtermne);
                sigNES_forone=[sigNESpo',sigNESne']';
                sigfdrp_forone=[sigfdrppo',sigfdrpne']';
                GOnumber_all=vertcat(GOnumber_all,sigGOnum_forone);
                GOterm_all=vertcat(GOterm_all,sigGOterm_forone);
                NES_all=[NES_all',sigNES_forone']';
                fdrp_all=[fdrp_all',sigfdrp_forone']';
                index=[index',k*ones(size(sigNES_forone,1),1)']';
                experiment=[experiment',i*ones(size(sigNES_forone,1),1)']';
            else
                NES=table2array(data(change_index(k)+1:end,"Var6"));
                GOnumber=data(change_index(k)+1:end,"Var1");
                GOterm=data(change_index(k)+1:end,"Var2");
                fdrp_change=fdrp(change_index(k)+1:end,1);
                sigfdrp_change=fdrp_change(find(fdrp_change<1));
                sigGOnumber=GOnumber(find(fdrp_change<1),1);
                sigGOterm=GOterm(find(fdrp_change<1),1);
                sigNES=NES(find(fdrp_change<1));
                po_sigNES=find(sigNES>0);
                ne_sigNES=find(sigNES<0);
                if size(po_sigNES,1)>topnumer
                    [~,index_po]=maxk(sigNES(po_sigNES),topnumer);
                    sigGOnumpo=sigGOnumber(po_sigNES(index_po),1);
                    sigGOtermpo=sigGOterm(po_sigNES(index_po),1);
                    sigNESpo=sigNES(po_sigNES(index_po),1);
                    sigfdrppo=sigfdrp_change(po_sigNES(index_po),1);
                else
                    sigGOnumpo=sigGOnumber(po_sigNES,1);
                    sigGOtermpo=sigGOterm(po_sigNES,1);
                    sigNESpo=sigNES(po_sigNES,1);
                    sigfdrppo=sigfdrp_change(po_sigNES,1);
                end
                if size(ne_sigNES,1)>topnumer
                    [~,index_ne]=mink(sigNES(ne_sigNES),topnumer);
                    sigGOnumne=sigGOnumber(ne_sigNES(index_ne),1);
                    sigGOtermne=sigGOterm(ne_sigNES(index_ne),1);
                    sigNESne=sigNES(ne_sigNES(index_ne),1);
                    sigfdrpne=sigfdrp_change(ne_sigNES(index_ne),1);
                else
                    sigGOnumne=sigGOnumber(ne_sigNES,1);
                    sigGOtermne=sigGOterm(ne_sigNES,1);
                    sigNESne=sigNES(ne_sigNES,1);
                    sigfdrpne=sigfdrp_change(ne_sigNES,1);
                end
                sigGOnum_forone=vertcat(sigGOnumpo,sigGOnumne);
                sigGOterm_forone=vertcat(sigGOtermpo,sigGOtermne);
                sigNES_forone=[sigNESpo',sigNESne']';
                sigfdrp_forone=[sigfdrppo',sigfdrpne']';
                GOnumber_all=vertcat(GOnumber_all,sigGOnum_forone);
                GOterm_all=vertcat(GOterm_all,sigGOterm_forone);
                NES_all=[NES_all',sigNES_forone']';
                fdrp_all=[fdrp_all',sigfdrp_forone']';
                index=[index',k*ones(size(sigNES_forone,1),1)']';
                experiment=[experiment',i*ones(size(sigNES_forone,1),1)']';
            end
        end
    end
end